#!/bin/bash
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# interactive shell mods
if [[ $- = *i* ]]; then

  # inside distrobox
  if [ -n "$container" ] || [ -f /run/.containerenv ] || [ -f /.dockerenv ]; then
    export LP_PS1_PREFIX="📦 $CONTAINER_ID"
    export LP_ENABLE_SHLVL=0
  fi
  export LP_USER_ALWAYS=0

  # load liquit prompt
  source ~/.custom/liquidprompt/liquidprompt
  source ~/.custom/liquidprompt-powerline/powerline.theme
  lp_theme powerline_full

  source ~/.custom/sensible.bash

  source ~/.custom/commacd.sh

  alias ll='ls -l'
  alias l='ls -lA'


  # fix for opening nano inside of tmux
  export TERM=xterm

  alias dc='docker compose'
  alias dcu='docker compose up -d --pull always --remove-orphans'
  alias dcb='docker compose --progress=plain build'
  alias dcub='docker compose up -d --pull always --build --remove-orphans'
  alias dcbu=dcub
  alias dcl='docker compose logs -f -n 100'
  alias dcul='dcu && dcl'
  alias dcr='docker compose restart'

  alias rsync='rsync --info=progress2'

  alias dive="docker run -ti --rm  -v /var/run/docker.sock:/var/run/docker.sock docker.io/wagoodman/dive"
fi
