#!/bin/bash
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# interactive shell mods
if [[ $- = *i* ]]; then

  # inside distrobox
  if [ -n "$container" ] || [ -f /run/.containerenv ] || [ -f /.dockerenv ]; then
    export LP_PS1_PREFIX="📦 $CONTAINER_ID"
    export LP_ENABLE_SHLVL=0
  fi
  export LP_USER_ALWAYS=0

  # load liquit prompt
  source ~/.custom/liquidprompt/liquidprompt
  source ~/.custom/liquidprompt-powerline/powerline.theme
  lp_theme powerline_full

  source ~/.custom/sensible.bash

  source ~/.custom/commacd.sh

  alias l="ls -la"
fi
